= Review: The Unicorn Project

Contents

1.) Project summary
2.) Participants
3.) How to Contribute
4.) Topics
5.) Conclusion

PROJECT

In the spirit of distributed and asynchronous work, we are creating this “Continuous Book Review” for Gene Kim’s latest book, The Unicorn Project: A Novel about Developers, Digital Disruption, and Thriving in the Age of Data. The format, content, participants, opinions, ideas, etc will be determined by the participants as the review is created.

PARTICIPANTS

Matt Sicker, Senior Software Engineer (Jenkins Security), CloudBees [add more here about yourself, contact information]

Karen Taggart, Principal Customer Success Engineer, CloudBees, ktaggart@cloudbees.com, @AngryTechFeminist

HOW TO CONTRIBUTE

1.) Fork the review.
2.) Add your name and contact information to PARTICIPANTS section
3.) Write and edit away! Add to an existing topic, or create a new one. When you are adding an opinion, please write in the third person such as, “ Karen wants to learn more about functional programming because Maxine keeps using it so much in the book to solve and simplify problems.” Be sure to note quotations and use page numbers whenever possible. 
4.) Create a pull request.
5.) Repeat (except #2) as many times as you want.

TOPICS

BOOK SUMMARY

THINGS I WANT TO TRY/IMPLEMENT 

I REALLY AGREE WITH…

I REALLY DISAGREE WITH…

DIVERSITY AND INCLUSION


CONCLUSION

